//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryRepo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public string Id { get; set; }
        public string AspNetUserId { get; set; }
        public string Barcode { get; set; }
        public Nullable<decimal> SerialNumber { get; set; }
        public string DeviceTypeId { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ReceivingDate { get; set; }
        public Nullable<System.DateTime> WarrantyExpiryDate { get; set; }
        public string LocationId { get; set; }
        public string StatusId { get; set; }
        public Nullable<bool> Racked { get; set; }
        public string Remarks { get; set; }
        public string ItemLogId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ItemLog ItemLog { get; set; }
        public virtual Location Location { get; set; }
        public virtual Status Status { get; set; }
    }
}
