//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMSRepo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicFormColumn
    {
        public int Id { get; set; }
        public string ColumnName { get; set; }
        public string DataType { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> Min { get; set; }
        public Nullable<int> Max { get; set; }
        public bool IsNullable { get; set; }
        public bool IsPrimaryKey { get; set; }
        public Nullable<int> DynamicFormId { get; set; }
    
        public virtual DynamicForm DynamicForm { get; set; }
    }
}
